### PR TITLE
Added project files to the repository

### PR DESCRIPTION
**Pull request by EzaanBabar**
Corrected the PR to the UT repository

### CODE REVIEW

**Comment by jgretz** [comment]
code received

**Comment by EzaanBabar** [comment]
Awesome, feel free to reach out if you have any questions about the code. Thank you

**Comment by EzaanBabar** [comment]
Here is the descriptions/instructions to run the program. I apologize, they are not included in the repo. I can add them to the repo if needed.

Description of the program:

The program allows the user to upload a CSV file and process transactions within that file. The program displays
transactions, collections, and bad transactions. The program also has the functionality to clear tables (frontend),
clear cache (frontend), and reset system. Resetting the system includes clearing tables, clearing cache, as well as resetting
our backend database.

The stack for this project is as follows:
    Frontend - HTML, CSS, JS. (vanilla) 
    Backend - Python with Flask, and SQLite for efficiency and storage.

Instructions to run the program:

After the GitHub repository has been cloned, go to the terminal and run the following commands to ensure that Flask and Python are 
installed.

    python --version
    pip show Flask

If Flask is not installed, run this command to install.

    pip install Flask

To start the program, navigate to the project directory (app.py) and run:

    python app.py

**Comment by EzaanBabar** [comment]
Good Afternoon, 

I was wondering if there was an update in regard to my technical assessment.

Thank you!

**Pull request closed without merging**
